### ISSUE TITLE
Authenticate to CourtListener API

### ISSUE THREAD

**Issue by anseljh** [anseljh/casebot#7]
See note from Mike in #3

**Comment by mlissner** [comment]
Easiest thing here is to use the [Token Auth](https://www.courtlistener.com/api/rest-info/#token-auth). Just add a header:

``` python
request_headers = {'user-agent': config['General']['user_agent'],
                   'Authenticate': 'Token $YOUR_TOKEN}
```

You can see your token at the top of the rest documentation on the right or embedded in the Token Auth instructions.
